# Generated by Django 3.0.5 on 2020-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='idno',
            field=models.CharField(default='', max_length=15),
        ),
    ]
