# Generated by Django 3.0.5 on 2020-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200502_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cylinderType', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
