# Generated by Django 3.0.5 on 2020-05-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200503_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
