# Generated by Django 3.0.5 on 2020-05-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=70)),
                ('nationality', models.CharField(max_length=12)),
                ('add', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('photo', models.ImageField(upload_to='profile')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
