# Generated by Django 3.0.5 on 2020-05-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_connection_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='id',
        ),
        migrations.AlterField(
            model_name='connection',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.Registration'),
        ),
    ]
