# Generated by Django 3.0.5 on 2020-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200503_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='conn_date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
