# Generated by Django 3.0.5 on 2020-05-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20200503_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='custno',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='custoname',
            new_name='name',
        ),
    ]
