# Generated by Django 3.0.5 on 2020-05-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20200503_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Status'),
        ),
    ]
