# Generated by Django 3.0.5 on 2020-05-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20200503_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
