# Generated by Django 3.0.5 on 2020-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20200503_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='conn_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
